### ISSUE TITLE
Upgrade for Laravel v11.x

### ISSUE THREAD

**Issue by scarm01** [ip2location/ip2location-laravel#8]
Currently not working for laravel 11.x

**Comment by ip2location-com** [comment]
Hi @scarm01,

Can you specify which version of Laravel 11 that is not working with our library? We have tested in Laravel 11.1.4 and it's working fine. It would be help if you can attached the error message also.

**Comment by ip2location-com** [comment]
Hi @scarm01,

We noticed that there hasn't been any activity on this issue for some time. As a result, we're closing it to keep our issue tracker organized.

If you believe this issue is still relevant or if you have any further details to add, please feel free to reopen it or create a new issue. We appreciate your contribution and are here to help if you need any assistance.
